### ISSUE TITLE
cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mechlya** [fastmachinelearning/hls4ml#264]
Hello!

whene I compile the model I get this error 
 this is my first time using hls4mland I wonder if I have something setup wrong  !

hls_model.compile()
Writing HLS project
Done
build_lib.sh: line 14: g++: command not found
build_lib.sh: line 15: g++: command not found
build_lib.sh: line 16: g++: command not found
Traceback (most recent call last):

  File "<ipython-input-20-20374fcfe547>", line 1, in <module>
    hls_model.compile()

  File "/home/ahmed/anaconda3/lib/python3.8/site-packages/hls4ml/model/hls_model.py", line 402, in compile
    self._top_function_lib = ctypes.cdll.LoadLibrary(lib_name)

  File "/home/ahmed/anaconda3/lib/python3.8/ctypes/__init__.py", line 459, in LoadLibrary
    return self._dlltype(name)

  File "/home/ahmed/anaconda3/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: firmware/myproject-51a9dCAc.so: cannot open shared object file: No such file or directory

**Comment by vloncar** [comment]
You need to install the GCC compiler on your system. If this is Ubuntu or Debian Linux, you can do it with `sudo apt install build-essential`. If on CentOS, you can do `sudo yum group install "Development Tools"`

**Comment by mechlya** [comment]
After the completion I get this message
I don't know what it's mean


![image_2020-12-15_185207](https://user-images.githubusercontent.com/62614958/102252666-a2e1e900-3f06-11eb-88b1-1d2afcdcca50.png)

**Comment by vloncar** [comment]
Your model is too large, so you ran out of memory during synthesis. You need to use `io_stream` instead of `io_parallel` to have any chance of success.

**Comment by ribbles** [comment]
5y later and this didn't fix the issue :(
