### ISSUE TITLE
onnx version support?

### ISSUE THREAD

**Issue by rateixei** [fastmachinelearning/hls4ml#462]
Hello,

Does hls4ml support newer versions of onnx? 

We've tried setting up hls4ml with onnx version 1.10.2, which raised the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/src/hls4ml/hls4ml/__init__.py", line 5, in <module>
    from hls4ml import converters
  File "/src/hls4ml/hls4ml/converters/__init__.py", line 20, in <module>
    from hls4ml.converters.onnx_to_hls import onnx_to_hls, get_supported_onnx_layers, register_onnx_layer_handler
  File "/src/hls4ml/hls4ml/converters/onnx_to_hls.py", line 5, in <module>
    from onnx import ModelProto, GraphProto, NodeProto, TensorProto
  File "/usr/local/lib/python3.6/dist-packages/onnx/__init__.py", line 11, in <module>
    from onnx.external_data_helper import load_external_data_for_model, write_external_data_tensors, convert_model_to_external_data
  File "/usr/local/lib/python3.6/dist-packages/onnx/external_data_helper.py", line 14, in <module>
    from .onnx_pb import TensorProto, ModelProto
  File "/usr/local/lib/python3.6/dist-packages/onnx/onnx_pb.py", line 8, in <module>
    from .onnx_ml_pb2 import *  # noqa
  File "/usr/local/lib/python3.6/dist-packages/onnx/onnx_ml_pb2.py", line 22, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

Downgrading onnx to 1.9.0 works just fine. Is this expected?

cc @drankincms

**Comment by vloncar** [comment]
This looks like an issue with your protobuf installation. Did you already have the onnx package installed and you upgraded it?It is possible that protobuf dependency wasn't upgraded, this happens to me all the time.
